// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.CcfCoreStatus;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect CcfCoreStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CcfCoreStatusDataOnDemand: @Component;
    
    private Random CcfCoreStatusDataOnDemand.rnd = new java.security.SecureRandom();
    
    public boolean CcfCoreStatusDataOnDemand.modifyCcfCoreStatus(CcfCoreStatus obj) {
        return false;
    }
    
}
