// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DirectionConfigDataOnDemand_Roo_Configurable {
    
    declare @type: DirectionConfigDataOnDemand: @Configurable;
    
}
