// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ExternalAppDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExternalAppIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExternalAppIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExternalAppIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ExternalAppIntegrationTest: @Transactional;
    
    @Autowired
    private ExternalAppDataOnDemand ExternalAppIntegrationTest.dod;
    
    @Test
    public void ExternalAppIntegrationTest.testCountExternalApps() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", dod.getRandomExternalApp());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        org.junit.Assert.assertTrue("Counter for 'ExternalApp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindExternalApp() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        org.junit.Assert.assertNotNull("Find method for 'ExternalApp' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ExternalApp' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindAllExternalApps() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", dod.getRandomExternalApp());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ExternalApp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ExternalApp> result = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findAllExternalApps();
        org.junit.Assert.assertNotNull("Find all method for 'ExternalApp' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ExternalApp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindExternalAppEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", dod.getRandomExternalApp());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ExternalApp> result = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalAppEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ExternalApp' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ExternalApp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        org.junit.Assert.assertNotNull("Find method for 'ExternalApp' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExternalApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ExternalApp' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExternalAppIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        boolean modified =  dod.modifyExternalApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp merged = (com.collabnet.ccf.ccfmaster.server.domain.ExternalApp) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ExternalApp' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExternalAppIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", dod.getRandomExternalApp());
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getNewTransientExternalApp(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ExternalApp' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ExternalApp' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExternalAppIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExternalApp' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ExternalApp' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id));
    }
    
}
