// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRuleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingRuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingRuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldMappingRuleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingRuleIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingRuleDataOnDemand FieldMappingRuleIntegrationTest.dod;
    
    @Test
    public void FieldMappingRuleIntegrationTest.testCountFieldMappingRules() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", dod.getRandomFieldMappingRule());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        org.junit.Assert.assertTrue("Counter for 'FieldMappingRule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindFieldMappingRule() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMappingRule' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FieldMappingRule' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindAllFieldMappingRules() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", dod.getRandomFieldMappingRule());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FieldMappingRule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findAllFieldMappingRules();
        org.junit.Assert.assertNotNull("Find all method for 'FieldMappingRule' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FieldMappingRule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindFieldMappingRuleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", dod.getRandomFieldMappingRule());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRuleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FieldMappingRule' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FieldMappingRule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMappingRule' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFieldMappingRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FieldMappingRule' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        boolean modified =  dod.modifyFieldMappingRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FieldMappingRule' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", dod.getRandomFieldMappingRule());
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getNewTransientFieldMappingRule(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FieldMappingRule' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FieldMappingRule' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingRule' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FieldMappingRule' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id));
    }
    
}
