// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplateDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingExternalAppTemplateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingExternalAppTemplateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldMappingExternalAppTemplateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingExternalAppTemplateIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingExternalAppTemplateDataOnDemand FieldMappingExternalAppTemplateIntegrationTest.dod;
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testCountFieldMappingExternalAppTemplates() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", dod.getRandomFieldMappingExternalAppTemplate());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.countFieldMappingExternalAppTemplates();
        org.junit.Assert.assertTrue("Counter for 'FieldMappingExternalAppTemplate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testFindFieldMappingExternalAppTemplate() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate obj = dod.getRandomFieldMappingExternalAppTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMappingExternalAppTemplate' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FieldMappingExternalAppTemplate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testFindAllFieldMappingExternalAppTemplates() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", dod.getRandomFieldMappingExternalAppTemplate());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.countFieldMappingExternalAppTemplates();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FieldMappingExternalAppTemplate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findAllFieldMappingExternalAppTemplates();
        org.junit.Assert.assertNotNull("Find all method for 'FieldMappingExternalAppTemplate' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FieldMappingExternalAppTemplate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testFindFieldMappingExternalAppTemplateEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", dod.getRandomFieldMappingExternalAppTemplate());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.countFieldMappingExternalAppTemplates();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplateEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FieldMappingExternalAppTemplate' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FieldMappingExternalAppTemplate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate obj = dod.getRandomFieldMappingExternalAppTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMappingExternalAppTemplate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFieldMappingExternalAppTemplate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FieldMappingExternalAppTemplate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate obj = dod.getRandomFieldMappingExternalAppTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(id);
        boolean modified =  dod.modifyFieldMappingExternalAppTemplate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FieldMappingExternalAppTemplate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", dod.getRandomFieldMappingExternalAppTemplate());
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate obj = dod.getNewTransientFieldMappingExternalAppTemplate(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FieldMappingExternalAppTemplate' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FieldMappingExternalAppTemplate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FieldMappingExternalAppTemplateIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate obj = dod.getRandomFieldMappingExternalAppTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMappingExternalAppTemplate' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FieldMappingExternalAppTemplate' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(id));
    }
    
}
