// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingLandscapeTemplate;
import java.util.List;
import org.springframework.stereotype.Component;

privileged aspect FieldMappingLandscapeTemplateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FieldMappingLandscapeTemplateDataOnDemand: @Component;
    
    private List<FieldMappingLandscapeTemplate> FieldMappingLandscapeTemplateDataOnDemand.data;
    
    private void FieldMappingLandscapeTemplateDataOnDemand.setParent(FieldMappingLandscapeTemplate obj, int index) {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape parent = landscapeDataOnDemand.getRandomLandscape();
        obj.setParent(parent);
    }
    
    private void FieldMappingLandscapeTemplateDataOnDemand.setName(FieldMappingLandscapeTemplate obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    private void FieldMappingLandscapeTemplateDataOnDemand.setDirection(FieldMappingLandscapeTemplate obj, int index) {
        com.collabnet.ccf.ccfmaster.server.domain.Directions direction = com.collabnet.ccf.ccfmaster.server.domain.Directions.class.getEnumConstants()[0];
        obj.setDirection(direction);
    }
    
    private void FieldMappingLandscapeTemplateDataOnDemand.setKind(FieldMappingLandscapeTemplate obj, int index) {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingKind kind = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingKind.class.getEnumConstants()[0];
        obj.setKind(kind);
    }
    
    public FieldMappingLandscapeTemplate FieldMappingLandscapeTemplateDataOnDemand.getSpecificFieldMappingLandscapeTemplate(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        FieldMappingLandscapeTemplate obj = data.get(index);
        return FieldMappingLandscapeTemplate.findFieldMappingLandscapeTemplate(obj.getId());
    }
    
    public FieldMappingLandscapeTemplate FieldMappingLandscapeTemplateDataOnDemand.getRandomFieldMappingLandscapeTemplate() {
        init();
        FieldMappingLandscapeTemplate obj = data.get(rnd.nextInt(data.size()));
        return FieldMappingLandscapeTemplate.findFieldMappingLandscapeTemplate(obj.getId());
    }
    
    public boolean FieldMappingLandscapeTemplateDataOnDemand.modifyFieldMappingLandscapeTemplate(FieldMappingLandscapeTemplate obj) {
        return false;
    }
    
    public void FieldMappingLandscapeTemplateDataOnDemand.init() {
        data = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingLandscapeTemplate.findFieldMappingLandscapeTemplateEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'FieldMappingLandscapeTemplate' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingLandscapeTemplate>();
        for (int i = 0; i < 10; i++) {
            com.collabnet.ccf.ccfmaster.server.domain.FieldMappingLandscapeTemplate obj = getNewTransientFieldMappingLandscapeTemplate(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
