// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldMappingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingDataOnDemand FieldMappingIntegrationTest.dod;
    
    @Test
    public void FieldMappingIntegrationTest.testCountFieldMappings() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", dod.getRandomFieldMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        org.junit.Assert.assertTrue("Counter for 'FieldMapping' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindFieldMapping() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMapping' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FieldMapping' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindAllFieldMappings() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", dod.getRandomFieldMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FieldMapping', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMapping> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findAllFieldMappings();
        org.junit.Assert.assertNotNull("Find all method for 'FieldMapping' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FieldMapping' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindFieldMappingEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", dod.getRandomFieldMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMapping> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMappingEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FieldMapping' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FieldMapping' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        org.junit.Assert.assertNotNull("Find method for 'FieldMapping' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFieldMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FieldMapping' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        boolean modified =  dod.modifyFieldMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMapping) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'FieldMapping' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldMappingIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", dod.getRandomFieldMapping());
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getNewTransientFieldMapping(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FieldMapping' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FieldMapping' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FieldMappingIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'FieldMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FieldMapping' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id));
    }
    
}
