// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.HospitalEntryDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HospitalEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HospitalEntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HospitalEntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: HospitalEntryIntegrationTest: @Transactional;
    
    @Autowired
    private HospitalEntryDataOnDemand HospitalEntryIntegrationTest.dod;
    
    @Test
    public void HospitalEntryIntegrationTest.testCountHospitalEntrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", dod.getRandomHospitalEntry());
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        org.junit.Assert.assertTrue("Counter for 'HospitalEntry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindHospitalEntry() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        org.junit.Assert.assertNotNull("Find method for 'HospitalEntry' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'HospitalEntry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindAllHospitalEntrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", dod.getRandomHospitalEntry());
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'HospitalEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry> result = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findAllHospitalEntrys();
        org.junit.Assert.assertNotNull("Find all method for 'HospitalEntry' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'HospitalEntry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindHospitalEntryEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", dod.getRandomHospitalEntry());
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry> result = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntryEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'HospitalEntry' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'HospitalEntry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        org.junit.Assert.assertNotNull("Find method for 'HospitalEntry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHospitalEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'HospitalEntry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        boolean modified =  dod.modifyHospitalEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry merged = (com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'HospitalEntry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", dod.getRandomHospitalEntry());
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getNewTransientHospitalEntry(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'HospitalEntry' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'HospitalEntry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'HospitalEntry' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'HospitalEntry' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id));
    }
    
}
