// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.LandscapeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LandscapeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LandscapeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LandscapeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LandscapeIntegrationTest: @Transactional;
    
    @Autowired
    private LandscapeDataOnDemand LandscapeIntegrationTest.dod;
    
    @Test
    public void LandscapeIntegrationTest.testCountLandscapes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", dod.getRandomLandscape());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        org.junit.Assert.assertTrue("Counter for 'Landscape' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindLandscape() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        org.junit.Assert.assertNotNull("Find method for 'Landscape' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Landscape' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindAllLandscapes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", dod.getRandomLandscape());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Landscape', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Landscape> result = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findAllLandscapes();
        org.junit.Assert.assertNotNull("Find all method for 'Landscape' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Landscape' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindLandscapeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", dod.getRandomLandscape());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Landscape> result = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscapeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Landscape' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Landscape' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LandscapeIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        org.junit.Assert.assertNotNull("Find method for 'Landscape' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLandscape(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Landscape' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LandscapeIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        boolean modified =  dod.modifyLandscape(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.Landscape merged = (com.collabnet.ccf.ccfmaster.server.domain.Landscape) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Landscape' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LandscapeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", dod.getRandomLandscape());
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getNewTransientLandscape(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Landscape' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Landscape' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LandscapeIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Landscape' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Landscape' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id));
    }
    
}
