// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.LandscapeConfig;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect LandscapeConfigDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LandscapeConfigDataOnDemand: @Component;
    
    private Random LandscapeConfigDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<LandscapeConfig> LandscapeConfigDataOnDemand.data;
    
    private void LandscapeConfigDataOnDemand.setLandscape(LandscapeConfig obj, int index) {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape landscape = landscapeDataOnDemand.getRandomLandscape();
        obj.setLandscape(landscape);
    }
    
    private void LandscapeConfigDataOnDemand.setName(LandscapeConfig obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    private void LandscapeConfigDataOnDemand.setVal(LandscapeConfig obj, int index) {
        java.lang.String val = "val_" + index;
        if (val.length() > 10485760) {
            val = val.substring(0, 10485760);
        }
        obj.setVal(val);
    }
    
    public LandscapeConfig LandscapeConfigDataOnDemand.getSpecificLandscapeConfig(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        LandscapeConfig obj = data.get(index);
        return LandscapeConfig.findLandscapeConfig(obj.getId());
    }
    
    public LandscapeConfig LandscapeConfigDataOnDemand.getRandomLandscapeConfig() {
        init();
        LandscapeConfig obj = data.get(rnd.nextInt(data.size()));
        return LandscapeConfig.findLandscapeConfig(obj.getId());
    }
    
    public boolean LandscapeConfigDataOnDemand.modifyLandscapeConfig(LandscapeConfig obj) {
        return false;
    }
    
    public void LandscapeConfigDataOnDemand.init() {
        data = com.collabnet.ccf.ccfmaster.server.domain.LandscapeConfig.findLandscapeConfigEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'LandscapeConfig' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.collabnet.ccf.ccfmaster.server.domain.LandscapeConfig>();
        for (int i = 0; i < 10; i++) {
            com.collabnet.ccf.ccfmaster.server.domain.LandscapeConfig obj = getNewTransientLandscapeConfig(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
