// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfigDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticipantConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipantConfigIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticipantConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParticipantConfigIntegrationTest: @Transactional;
    
    @Autowired
    private ParticipantConfigDataOnDemand ParticipantConfigIntegrationTest.dod;
    
    @Test
    public void ParticipantConfigIntegrationTest.testCountParticipantConfigs() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", dod.getRandomParticipantConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        org.junit.Assert.assertTrue("Counter for 'ParticipantConfig' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindParticipantConfig() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        org.junit.Assert.assertNotNull("Find method for 'ParticipantConfig' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ParticipantConfig' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindAllParticipantConfigs() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", dod.getRandomParticipantConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ParticipantConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig> result = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findAllParticipantConfigs();
        org.junit.Assert.assertNotNull("Find all method for 'ParticipantConfig' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ParticipantConfig' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindParticipantConfigEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", dod.getRandomParticipantConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig> result = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfigEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ParticipantConfig' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ParticipantConfig' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        org.junit.Assert.assertNotNull("Find method for 'ParticipantConfig' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticipantConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ParticipantConfig' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        boolean modified =  dod.modifyParticipantConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig merged = (com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ParticipantConfig' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", dod.getRandomParticipantConfig());
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getNewTransientParticipantConfig(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ParticipantConfig' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ParticipantConfig' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParticipantConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ParticipantConfig' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id));
    }
    
}
