// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ParticipantDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticipantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticipantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParticipantIntegrationTest: @Transactional;
    
    @Autowired
    private ParticipantDataOnDemand ParticipantIntegrationTest.dod;
    
    @Test
    public void ParticipantIntegrationTest.testCountParticipants() {
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        org.junit.Assert.assertTrue("Counter for 'Participant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipant() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        org.junit.Assert.assertNotNull("Find method for 'Participant' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Participant' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindAllParticipants() {
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Participant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Participant> result = com.collabnet.ccf.ccfmaster.server.domain.Participant.findAllParticipants();
        org.junit.Assert.assertNotNull("Find all method for 'Participant' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Participant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipantEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Participant> result = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipantEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Participant' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Participant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticipantIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        org.junit.Assert.assertNotNull("Find method for 'Participant' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticipant(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Participant' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        boolean modified =  dod.modifyParticipant(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.Participant merged = (com.collabnet.ccf.ccfmaster.server.domain.Participant) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Participant' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getNewTransientParticipant(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Participant' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Participant' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticipantIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Participant' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id));
    }
    
}
