// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfigDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepositoryMappingDirectionConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @Transactional;
    
    @Autowired
    private RepositoryMappingDirectionConfigDataOnDemand RepositoryMappingDirectionConfigIntegrationTest.dod;
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testCountRepositoryMappingDirectionConfigs() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", dod.getRandomRepositoryMappingDirectionConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        org.junit.Assert.assertTrue("Counter for 'RepositoryMappingDirectionConfig' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindRepositoryMappingDirectionConfig() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMappingDirectionConfig' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RepositoryMappingDirectionConfig' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindAllRepositoryMappingDirectionConfigs() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", dod.getRandomRepositoryMappingDirectionConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RepositoryMappingDirectionConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findAllRepositoryMappingDirectionConfigs();
        org.junit.Assert.assertNotNull("Find all method for 'RepositoryMappingDirectionConfig' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RepositoryMappingDirectionConfig' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindRepositoryMappingDirectionConfigEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", dod.getRandomRepositoryMappingDirectionConfig());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfigEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RepositoryMappingDirectionConfig' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RepositoryMappingDirectionConfig' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMappingDirectionConfig' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRepositoryMappingDirectionConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RepositoryMappingDirectionConfig' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        boolean modified =  dod.modifyRepositoryMappingDirectionConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RepositoryMappingDirectionConfig' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", dod.getRandomRepositoryMappingDirectionConfig());
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getNewTransientRepositoryMappingDirectionConfig(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RepositoryMappingDirectionConfig' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RepositoryMappingDirectionConfig' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RepositoryMappingDirectionConfig' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id));
    }
    
}