// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepositoryMappingDirectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @Transactional;
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testCountRepositoryMappingDirections() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", dod.getRandomRepositoryMappingDirection());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        org.junit.Assert.assertTrue("Counter for 'RepositoryMappingDirection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindRepositoryMappingDirection() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMappingDirection' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RepositoryMappingDirection' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindAllRepositoryMappingDirections() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", dod.getRandomRepositoryMappingDirection());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RepositoryMappingDirection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findAllRepositoryMappingDirections();
        org.junit.Assert.assertNotNull("Find all method for 'RepositoryMappingDirection' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RepositoryMappingDirection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindRepositoryMappingDirectionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", dod.getRandomRepositoryMappingDirection());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirectionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RepositoryMappingDirection' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RepositoryMappingDirection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMappingDirection' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRepositoryMappingDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RepositoryMappingDirection' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        boolean modified =  dod.modifyRepositoryMappingDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RepositoryMappingDirection' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMappingDirection' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RepositoryMappingDirection' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id));
    }
    
}
