// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepositoryMappingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RepositoryMappingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingIntegrationTest: @Transactional;
    
    @Autowired
    private RepositoryMappingDataOnDemand RepositoryMappingIntegrationTest.dod;
    
    @Test
    public void RepositoryMappingIntegrationTest.testCountRepositoryMappings() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", dod.getRandomRepositoryMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        org.junit.Assert.assertTrue("Counter for 'RepositoryMapping' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindRepositoryMapping() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMapping' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RepositoryMapping' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindAllRepositoryMappings() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", dod.getRandomRepositoryMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RepositoryMapping', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findAllRepositoryMappings();
        org.junit.Assert.assertNotNull("Find all method for 'RepositoryMapping' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RepositoryMapping' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindRepositoryMappingEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", dod.getRandomRepositoryMapping());
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMappingEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RepositoryMapping' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RepositoryMapping' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        org.junit.Assert.assertNotNull("Find method for 'RepositoryMapping' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRepositoryMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RepositoryMapping' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        boolean modified =  dod.modifyRepositoryMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RepositoryMapping' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", dod.getRandomRepositoryMapping());
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getNewTransientRepositoryMapping(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RepositoryMapping' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RepositoryMapping' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RepositoryMapping' failed to provide an identifier", id);
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RepositoryMapping' with identifier '" + id + "'", com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id));
    }
    
}
